// TODO: The letters must be in pairs here, so it has more in common with plugboard config than rotor wiring. Might be worth looking at enforcing that.
import { RotorWiring } from "./Rotor";

export const ukwBWiring: RotorWiring = {
  A: "Y",
  B: "R",
  C: "U",
  D: "H",
  E: "Q",
  F: "S",
  G: "L",
  H: "D",
  I: "P",
  J: "X",
  K: "N",
  L: "G",
  M: "O",
  N: "K",
  O: "M",
  P: "I",
  Q: "E",
  R: "B",
  S: "F",
  T: "Z",
  U: "C",
  V: "W",
  W: "V",
  X: "J",
  Y: "A",
  Z: "T",
};
